blog/urls.py
from django.urls import path, re_path
from . import views 

app_name = 'blog'
urlpatterns = [
    # post views
    # path('', views.post_list, name='post_list'),
    # path('<slug:slug>/', views.PostDetailView.as_view(), name='post-detail'),
    path('the-loai/', views.genre_list, name='genre-list'),
    path('<slug:slug>/', views.post_detail, name='post-detail'),
    # path('the-loai/', views.GenreListView.as_view(), name='genre-list'),
    path('the-loai/<slug:slug>/', views.genre_detail, name='genre-detail'),
    path('chap/<slug:post_slug>/<slug:chap_slug>/',
          views.chap_detail,
          name='chap-detail'),
    path('chap/<slug:post_slug>/<slug:chap_slug>/report/', views.report_create_view, name='report-create'),
]

mysite/urls.py
from django.urls import path, include
from django.contrib import admin


from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

from users import views as user_views
from blog import views as views
from django.contrib.auth import views as auth_views

urlpatterns = [
        path('admin/', admin.site.urls),
        path('register/', user_views.register, name='register'),
        path('profile/', user_views.profile, name='profile'),
        path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
        path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
        path('password-reset/', 
                auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), 
                name='password_reset'),
        path('password-reset/done', 
                auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), 
                name='password_reset_done'),
        path('password-reset-confirm/<uidb64>/<token>/', 
                auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), 
                name='password_reset_confirm'),
        path('password-reset-complete/', 
                auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), 
                name='password_reset_complete'),
        path('', views.post_list, name='post-list'),
        path('blog/', include('blog.urls', namespace='blog')),
        path('oauth/', include('social_django.urls', namespace='social')),
        path('like/', views.like_post, name="like-post"),
        path('ajax/autocomplete/', views.autocomplete, name='ajax_autocomplete'),
        path('search/', views.search_list, name='search_list')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone 
from django.contrib.auth.models import User 
from django.urls import reverse

class PublishedManager(models.Manager): 
    def get_queryset(self): 
        return super(PublishedManager, self).get_queryset().filter(status='published')

STATUS_CHOICES = ( 
        ('draft', 'Draft'), 
        ('published', 'Published'), 
    )

class Post(models.Model): 
    title = models.CharField(max_length=250) 
    slug = models.SlugField(max_length=250, unique=True)
    user = models.ForeignKey(User, 
                               on_delete=models.CASCADE)
    body = models.TextField()
    author = models.CharField(max_length=250, default="Chưa xác định") 
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    publish = models.DateTimeField(default=timezone.now) 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    status = models.CharField(max_length=10,  
                              choices=STATUS_CHOICES, 
                              default='draft') 
    
    objects = models.Manager() # The default manager. 
    published = PublishedManager() # Our custom manager.
    image_cover = models.ImageField(upload_to="cover_img", default="images/None/no-img.jpg", blank=True) 

    class Meta: 
        ordering = ('-publish',) 

    def __str__(self): 
        return self.title
    
    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('blog:post-detail',
                       args=[self.slug])

class Genre(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique=True)
    posts = models.ManyToManyField(Post)
    class Meta: 
        ordering = ('name',) 
        verbose_name_plural = "genres"

    def __str__(self): 
        return self.name
    
    def get_absolute_url(self):
        return reverse('blog:genre-detail',
                       args=[self.slug])

class Chap(models.Model):
    post = models.ForeignKey(
        Post, related_name='chaps',
        on_delete=models.CASCADE,
    )
    title = models.CharField(max_length=250) 
    slug = models.SlugField(max_length=250, unique=True, default="")
    user = models.ForeignKey(User, 
                               on_delete=models.CASCADE)
    publish = models.DateTimeField(default=timezone.now) 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    status = models.CharField(max_length=10,  
                              choices=STATUS_CHOICES, 
                              default='draft') 
    
    objects = models.Manager() # The default manager. 
    published = PublishedManager() # Our custom manager.

    class Meta: 
        ordering = ('-title',)

    def __str__(self): 
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:chap-detail',
                       args=[self.post.slug, self.slug])

class ChapImage(models.Model):
    chap = models.ForeignKey(Chap, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to="comics/headers/", default="")

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reply = models.ForeignKey('Comment', null=True, related_name="replies", on_delete=models.CASCADE)
    content = models.TextField(max_length=160)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '{}-{}'.format(self.post.title, str(self.user.username))

class Report(models.Model):
    reporting_url = models.URLField()
    message = models.TextField()

    def __str__(self):
        return self.reporting_url

blog/forms.py
from django import forms
from .models import Post, Comment
from django.contrib.auth.models import User
from .models import Report

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = [
            'reporting_url',
            'message'
        ]
        
class CommentForm(forms.ModelForm):
    content = forms.CharField(label="", widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Text goes here!!!', 'rows':'4', 'cols':'50'}))
    class Meta:
        model = Comment
        fields = ('content',)

blog/views.py
from django.shortcuts import render, get_object_or_404 , redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView, DetailView
from .models import Post, Chap, Genre, Comment
from .forms import *
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template.loader import render_to_string
from django.db.models import Q

def navigation(request):
    genre_list = Genre.objects.all()
    return({'genre_list': genre_list})


def post_list(request):
    post_list = Post.published.all()
    paginator = Paginator(post_list, 12) 
    new_chaps = Chap.published.all().reverse()
    rank_like = sorted(post_list, key= lambda t: t.total_likes(), reverse=True)   

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if page is None:
        start_index = 0
        end_index = 7
    else:
        (start_index, end_index) = proper_pagination(posts, index=4)

    page_range = list(paginator.page_range)[start_index:end_index]
    context = {
        'posts': posts,
        'page_range': page_range,
        'new_chaps': new_chaps,
        'rank_like': rank_like,
    }

    return render(request, 'blog/post_list.html', context)

def post_detail(request, slug): 
    genre_list = Genre.objects.all()
    post = get_object_or_404(Post, slug=slug,
                                   status='published')
    comments = Comment.objects.filter(post=post, reply=None).order_by('-id')
    genre_list = genre_list.filter(posts=post)
    is_liked = False

    if post.likes.filter(id=request.user.id).exists():
        is_liked = True
    
    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            content = request.POST.get('content')
            reply_id = request.POST.get('comment_id')
            comment_qs = None
            if reply_id:
                comment_qs = Comment.objects.get(id=reply_id)
            comment = Comment.objects.create(post=post, user=request.user, content=content, reply=comment_qs)
            comment.save()
            # return HttpResponseRedirect(post.get_absolute_url())
    else:
        comment_form= CommentForm()


    context = {
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
        'genre_list': genre_list,
        'comments': comments,
        'comment_form': comment_form,
    }
    if request.is_ajax():
        html = render_to_string('blog/comments.html', context, request=request)
        return JsonResponse({'form': html})
    return render(request, 'blog/post_detail.html', context)

def chap_detail(request, post_slug, chap_slug):
    post = get_object_or_404(Post, slug=post_slug,
                                   status='published')
    chap = get_object_or_404(Chap, post=post , slug=chap_slug,
                                   status='published')
    pre_chap = post.chaps.filter(title__lt=chap.title).order_by('-title').first()
    next_chap = post.chaps.filter(title__gt=chap.title).order_by('title').first()

    return render(request,
                  'blog/chap_detail.html',
                  {'chap': chap,
                  'next_chap': next_chap,
                  'pre_chap': pre_chap,})

def genre_list(request):
    genres = Genre.objects.all()
    return render(request,
                  'blog/genre_list.html',
                  {'genres': genres})

def genre_detail(request, slug):
    genre = get_object_or_404(Genre, slug=slug)
    post_list =  genre.posts.all()

    paginator = Paginator(post_list, 6)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if page is None:
        start_index = 0
        end_index = 7
    else:
        (start_index, end_index) = proper_pagination(posts, index=4)

    page_range = list(paginator.page_range)[start_index:end_index]
    context = {
        'genre': genre,
        'posts': posts,
        'page_range': page_range,
    }
    return render(request, 'blog/genre_detail.html', context)

class PostListView(ListView):
    model = Post
    paginate_by = 100  # if pagination is desired
    template_name = "blog/post_list.html"
    context_object_name = 'posts'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class PostDetailView(DetailView):

    model = Post
    template_name = "blog/post_detail.html"
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class GenreListView(ListView):
    model = Genre
    paginate_by = 100  # if pagination is desired
    template_name = "blog/genre_list.html"
    context_object_name = 'genres'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

class GenreDetailView(DetailView):
    model = Genre
    paginate_by = 100  # if pagination is desired
    template_name = "blog/genre_detail.html"
    context_object_name = 'genre'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

def like_post(request):
    # post = get_object_or_404(Post, id=request.POST.get('post_id'))
    post = get_object_or_404(Post, id=request.POST.get('id'))
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else:
        post.likes.add(request.user)
        is_liked = True
    context = {
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
    }
    if request.is_ajax():
        html = render_to_string('blog/like_section.html', context, request=request)
        return JsonResponse({'form': html})

def autocomplete(request):
    if request.is_ajax():
        queryset = Post.published.filter(title__contains=request.GET.get('search', None))
        list = []        
        for i in queryset:
            list.append(i.title)
        data = {
            'list': list,
        }
        return JsonResponse(data)

def search_list(request):
    query = request.GET.get("q")
    post_list = Post.published.all()
    post_list = post_list.filter(Q(title__contains=query))
    paginator = Paginator(post_list, 4) 
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if page is None:
        start_index = 0
        end_index = 7
    else:
        (start_index, end_index) = proper_pagination(posts, index=4)

    page_range = list(paginator.page_range)[start_index:end_index]
    context = {
        'posts': posts,
        'page_range': page_range,
    }

    return render(request, 'blog/search_list.html', context)


def proper_pagination(posts, index):
    start_index = 0
    end_index = 7
    if posts.number > index:
        start_index = posts.number - index
        end_index = start_index + end_index
    return (start_index, end_index)

def report_create_view(request, post_slug, chap_slug):
    form = ReportForm(request.POST or None)
    url_report = "http://127.0.0.1:8000"+request.get_full_path()
    url_report = url_report.replace('/report', '')
    form.reporting_url = url_report
    if form.is_valid():
        form.save()
    context = {
        'form' : form,
        'url_report' : url_report
    }
    if form.is_valid():
        return redirect(url_report)
    return  render(request, "blog/reports_create.html", context)

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css" rel="stylesheet" type="text/css" />
    <link type="text/css" href="{% static "css/blog.css" %}" rel="stylesheet" media="screen">
    <link type="text/css" href="{% static "css/main.css" %}" rel="stylesheet" media="screen">
    <style>
        input {
            max-width: 12em
        }

        .content-section {
            max-width: 500px;
            margin: 0 auto;
        }
    </style>
</head>

<body>
    {% include "navbar.html" %}
    <div id="content" class="page-content">
        <div class="container-fluid">
            {% if messages %} {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{message }}
            </div>
            {% endfor %} {% endif %} {% block content %} {% endblock %}
        </div>
    </div>
    {% include "footer.html" %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
        integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <script type="text/javascript">
        jQuery(function () {
            $("#id_input").on('keyup', function () {
                var value = $(this).val();
                $.ajax({
                    url: "{% url 'ajax_autocomplete' %}",
                    data: {
                        'search': value
                    },
                    dataType: 'json',
                    success: function (data) {
                        list = data.list;
                        $("#id_input").autocomplete({
                            source: list,
                            minLength: 1
                        });
                    }
                });
            });
        });
        $(document).ready(function (event) {
            $('.dropdown-toggle').dropdown()

            $('.reply-btn').click(function () {
                $(this).parent().parent().next('.replied-comments').fadeToggle()
            });

            $(document).on('click', '#like', function (event) {
                event.preventDefault();
                var pk = $(this).attr('value');
                $.ajax({
                    type: 'POST',
                    url: '{% url "like-post" %}',
                    data: { 'id': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                    dataType: 'json',
                    success: function (response) {
                        $('#like-section').html(response['form'])
                        console.log($('#like-section').html(response['form']));
                    },
                    error: function (rs, e) {
                        console.log(rs.responseText);
                    },
                });
            });

            $(document).on('submit', '.comment-form', function (event) {
                event.preventDefault();
                console.log($(this).serialize());
                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: $(this).serialize(),
                    dataType: 'json',
                    success: function (response) {
                        $('.main-comment-section').html(response['form']);
                        $('textarea').val('');
                        $('.reply-btn').click(function () {
                            $(this).parent().parent().next('.replied-comments').fadeToggle();
                            $('textarea').val('');
                        });
                    },
                    error: function (rs, e) {
                        console.log(rs.responseText);
                    },
                });
            });
            $(document).on('submit', '.reply-form', function (event) {
                event.preventDefault();
                console.log($(this).serialize());
                $.ajax({
                    type: 'POST',
                    url: $(this).attr('action'),
                    data: $(this).serialize(),
                    dataType: 'json',
                    success: function (response) {
                        $('.main-comment-section').html(response['form']);
                        $('textarea').val('');
                        $('.reply-btn').click(function () {
                            $(this).parent().parent().next('.replied-comments').fadeToggle();
                            $('textarea').val('');
                            $('.dropdown-toggle').dropdown();
                        });
                    },
                    error: function (rs, e) {
                        console.log(rs.responseText);
                    },
                });
            });
        });
    </script>
    {% block javascript %}
    {% endblock javascript %}
</body>

</html>

blog/templates/footer.html
<footer class="footer bg-dark">
    <div class="row">
        <div class="col-5">
            <h5>Đồ án môn học Lập trình ứng dụng Web - NT208.K21.ANTT</h5>
            <p>Đề tài: Trang Web sách/(truyện), lập chỉ mục và tìm kiếm (auto complete, suggestion)</p>
        </div>
        <div class="col-4">
            <h5>Danh sách nhóm</h5>
            <p>Lê Qúy Hiển - 16520362</p>
            <p>Nguyễn Tuấn Khôi - 16520611</p>
            <p>Hoàng Hữu Thắng - 16521096</p>
        </div>
        <div class="col-3">
            <h5>Giáo viên hướng dẫn</h5>
            <p>Trần Tuấn Dũng</p>
            <small><a href="https://dungtran.top/">Trang web của thầy</a></small>
        </div>
    </div>
</footer>

blog/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'post-list' %}">
    <img src="../../media/logo/logo.jpg" class="d-inline-block align-top img-fluid" width="80" alt="#">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <a class="navbar-item nav-link" href="{% url 'profile' %}">Profile</a>
  </div> -->

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Thể Loại
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% for genre_item in genre_list %}
            <a class="dropdown-item" href="{{ genre_item.get_absolute_url }}">{{ genre_item.name }}</a>
          {% endfor %}
        </div>
      </li>
      <!-- <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:genre-list' %}">Thể Loại</a>
      </li> -->
    </ul>
    <form class="form-inline my-2 my-lg-0 nav-item" action="{% url 'search_list' %}">
      <input type="text" id="id_input" name="q" value="{{ request.get.q }}" class="form-control mr-sm-2"
        placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <ul class="navbar-nav ml-auto">

      {% if request.user.is_authenticated %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          {% if request.user.profile.image %}
          <img class="rounded-circle account-img" src="{{ request.user.profile.image.url }}" width="30px" height="30px">
          {% else %}
          <img src="../../media/images/None/default.jpg">
          {% endif %}
          <span>{{ request.user|capfirst }}</span>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'profile' %}">Profile</a>
          <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </div>
        {% else %}
        <a class="dropdown-item" href="{% url 'login' %}">Login</a>
        <a class="dropdown-item" href="{% url 'register' %}">Register</a>
      </li>
      {% endif %}
    </ul>

  </div>
</nav>

blog/templates/pagination.html
<ul class="pagination">
  {% if posts.has_previous %}
    {% if 'q' in request.GET %}
    <li class="page-item">
      <a href="?q={{ request.get.q }}&&page={{ posts.previous_page_number }}" class="page-link">&laquo;</a>
    </li>
    {% else %}
    <li class="page-item">
      <a href="?page={{ posts.previous_page_number }}" class="page-link">&laquo;</a>
    </li>
    {% endif %}
  {% endif %}

  {% for p in page_range %}
    {% if posts.number == p %}
      {% if 'q' in request.GET %}
        <li class="page-item active">
          <a href="?q={{ request.get.q }}&&page={{ p }}" class="page-link">{{ p }}</a>
        </li>
      {% else %}
        <li class="page-item active">
          <a href="?page={{ p }}" class="page-link">{{ p }}</a>
        </li>
      {% endif %}
    {% else %}
      {% if 'q' in request.GET %}
        <li class="page-item">
          <a href="?q={{ request.get.q }}&&page={{ p }}" class="page-link">{{ p }}</a>
        </li>
      {% else %}
        <li class="page-item">
          <a href="?page={{ p }}" class="page-link">{{ p }}</a>
        </li>
      {% endif %}
    {% endif %}
  {% endfor %}

  {% if posts.has_next %}
    {% if 'q' in request.GET %}
      <li class="page-item">
        <a href="?q={{ request.get.q }}&&page={{ posts.next_page_number }}" class="page-link">&raquo;</a>
      </li>
    {% else %}
      <li class="page-item">
        <a href="?page={{ posts.next_page_number }}" class="page-link">&raquo;</a>
      </li>
    {% endif %}
  {% endif %}
</ul>